### ISSUE TITLE
Search is kinda fucked up

### ISSUE THREAD

**Issue by RealRainbuu** [Modern-Modpacks/kjspkg-lookup#1]
When searching, some things are buggy. for example, searching "crea" doesn't come up with anything but "creat" comes up with 3 things, including Craftjs which has nothing to do with creat(e).

![image](https://github.com/Modern-Modpacks/kjspkg-lookup/assets/77862418/f3b3b27c-c8d8-4d75-92a6-868385df9836)

Also there should be more create packages that show up like wtf

**Comment by Gcat101** [comment]
wait when did you leave this I didn't see it lmao

**Comment by Gcat101** [comment]
I don't think I can really do anything with it lmao, I'm using the fuzz thing that I'm also using in kjspkg itself

**Comment by tizu69** [comment]
#2 resolved this.
